// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaPKYm4BSvESPetcfPmH9RfIOm0QFmbQU',
    appId: '1:385772200349:web:da884a514bfecfcefdcf74',
    messagingSenderId: '385772200349',
    projectId: 'mynotes-project-mulder-android',
    authDomain: 'mynotes-project-mulder-android.firebaseapp.com',
    storageBucket: 'mynotes-project-mulder-android.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjvAAA0_Yb06hQW1ZMyumMgh8XDcxoSgQ',
    appId: '1:385772200349:android:43b5f99732132856fdcf74',
    messagingSenderId: '385772200349',
    projectId: 'mynotes-project-mulder-android',
    storageBucket: 'mynotes-project-mulder-android.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs3aY55i98PJE2IJc-5y6M1oZsgGNEL8E',
    appId: '1:385772200349:ios:16f1fe35f28a6d16fdcf74',
    messagingSenderId: '385772200349',
    projectId: 'mynotes-project-mulder-android',
    storageBucket: 'mynotes-project-mulder-android.appspot.com',
    iosClientId: '385772200349-k43mmknssaqs2ammdifv13jscggn79bn.apps.googleusercontent.com',
    iosBundleId: 'oosthuizen.mulder.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs3aY55i98PJE2IJc-5y6M1oZsgGNEL8E',
    appId: '1:385772200349:ios:16f1fe35f28a6d16fdcf74',
    messagingSenderId: '385772200349',
    projectId: 'mynotes-project-mulder-android',
    storageBucket: 'mynotes-project-mulder-android.appspot.com',
    iosClientId: '385772200349-k43mmknssaqs2ammdifv13jscggn79bn.apps.googleusercontent.com',
    iosBundleId: 'oosthuizen.mulder.mynotes',
  );
}
